# Pre-commit configuration for sidan-binance-sdk (Python 3.8+, uv-managed project)
# - Fast, opinionated lint/format via Ruff
# - Safety & hygiene checks
# - Static typing via mypy
#
# Usage:
#   uv pip install pre-commit  # or pip install pre-commit
#   pre-commit install         # install git hooks
#   pre-commit run -a          # run on all files once

minimum_pre_commit_version: "3.5.0"

default_language_version:
  python: python3.11

default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
        exclude: ^tests/
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

  # Ruff: linter & formatter (use ruff-format instead of black)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  # Optional modernization of syntax to target a specific Python version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  # Static typing (reads config from pyproject.toml)
  # Note: Disabled due to extensive architectural issues with class-scoped imports
  # Can be re-enabled after refactoring the codebase structure
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #       args: ["--config-file=pyproject.toml"]
  #       additional_dependencies:
  #         - types-requests
  #       exclude: ^(tests/|examples/|docs/|binance/websocket/spot/websocket_api/__init__.py)

  # Spell check common mistakes in prose/code (tune ignore list for project terms)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "crate,statics,trough,binance,verion,avaliable,parameteres,permissons,parametes,withdrawl,receving"]
        exclude: ^(CHANGELOG\.md|.*\.lock)$

# --- Optional: enable hooks at push as well ---
# default_stages: [commit, push]
